apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sas-viya-letsencrypt-issuer
  namespace: viya
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: unknown@sas.com
    privateKeySecretRef:
      name: sas-viya-letsencrypt-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux