apiVersion: builtin
kind: PatchTransformer
metadata:
  name: change-viya-volume-storage-class
patch: |-
  kind: PodTemplate
  metadata:
    name: change-viya-volume-storage-class
  template: 
    spec: 
      volumes:
      - \$patch: delete
        name: viya
      - name: viya
        hostPath:
          path: /mnt/sastmp/saswork
          type: Directory
target:
  kind: PodTemplate
  labelSelector: "sas.com/template-intent=sas-launcher"